#ifndef BASE_LOGGING_SYSLOG_H__
#define BASE_LOGGING_SYSLOG_H__

#define SYSLOG_EMERGENCY 0
#define SYSLOG_ALERT 1
#define SYSLOG_CIRTICAL 2
#define SYSLOG_ERROR 3
#define SYSLOG_WARNING 4
#define SYSLOG_NOTICE 5
#define SYSLOG_INFORMATIONAL 6
#define SYSLOG_DEBUG 7
#define SYSLOG_NODELAY 8
#define SYSLOG_DAEMON 24

#endif
